# Generated by Django 3.2.6 on 2021-08-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.CharField(choices=[('IND', 'India -- Default'), ('SG', 'Singapore')], default='IND', max_length=10),
        ),
    ]
