# Generated by Django 3.2.6 on 2021-08-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='product_quantity',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='label',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
